#!/usr/bin/env python3
"""WP-a01 Stage-3 comparator.

Reads the two independently generated vector files and compares them field-by-field,
byte-for-byte. Emits AGREEMENT_MANIFEST.md recording, for every vector, the
input -> canonical bytes -> preimage -> digest -> signature chain and the per-field
agreement result. The comparator is deliberately separate from both generators: the
generators never read each other; agreement is measured here, not inherited.

Exit codes: 0 = every field of every vector byte-identical; 1 = any mismatch or
missing vector/field; 2 = an output file is missing/unreadable.
"""
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
PY_OUT = HERE / "out" / "python_vectors.json"
NODE_OUT = HERE / "out" / "node_vectors.json"
MANIFEST = HERE / "AGREEMENT_MANIFEST.md"

ARTIFACT_FIELDS = [
    "hash_tag_hex", "sig_tag_hex", "jcs_body_hex", "hash_preimage_hex",
    "current", "suite_id_hex", "sig_preimage_hex", "signature_hex",
    "producer_pubkey_hex",
]
WITNESS_FIELDS = [
    "head", "witness_tag_hex", "suite_id_hex", "jcs_claim_hex",
    "witness_preimage_hex", "witness_signature_hex", "witness_pubkey_hex",
]


def load(path: Path):
    try:
        with path.open("r", encoding="utf-8") as f:
            return json.load(f)["vectors"]
    except Exception as e:  # noqa: BLE001 - report and exit, never guess
        print(f"ERROR reading {path}: {e}")
        sys.exit(2)


def short(hexstr: str, n: int = 16) -> str:
    return hexstr if len(hexstr) <= 2 * n else f"{hexstr[:n]}…{hexstr[-n:]} ({len(hexstr)//2} bytes)"


def main() -> int:
    py = load(PY_OUT)
    node = load(NODE_OUT)
    ids = sorted(set(py) | set(node))
    lines = [
        "# WP-α01 Stage-3 — Byte-agreement manifest",
        "",
        "> Generated by `compare_vectors.py` from `out/python_vectors.json` (Stage 3A) and",
        "> `out/node_vectors.json` (Stage 3B). The two generators were written independently",
        "> from the frozen normative text and never read each other; this manifest records",
        "> **which byte sequences they agreed on**, field by field.",
        "",
    ]
    mismatches = 0
    for vid in ids:
        a, b = py.get(vid), node.get(vid)
        lines.append(f"## {vid}")
        if a is None or b is None:
            lines.append(f"- **MISSING** in {'python' if a is None else 'node'} output")
            mismatches += 1
            lines.append("")
            continue
        fields = WITNESS_FIELDS if vid.startswith("W") else ARTIFACT_FIELDS
        for f in fields:
            va, vb = a.get(f), b.get(f)
            if va is None or vb is None:
                lines.append(f"- `{f}`: **MISSING** ({'python' if va is None else 'node'})")
                mismatches += 1
            elif va != vb:
                lines.append(f"- `{f}`: **MISMATCH**")
                lines.append(f"  - python: `{short(str(va))}`")
                lines.append(f"  - node:   `{short(str(vb))}`")
                mismatches += 1
            else:
                lines.append(f"- `{f}`: AGREE `{short(str(va))}`")
        extra_a = sorted(set(a) - set(fields))
        extra_b = sorted(set(b) - set(fields))
        if extra_a or extra_b:
            lines.append(f"- extra fields — python: {extra_a} node: {extra_b}")
        lines.append("")
    verdict = "ALL FIELDS BYTE-IDENTICAL" if mismatches == 0 else f"{mismatches} MISMATCH/MISSING FIELD(S)"
    lines.insert(6, f"**Result: {verdict}** across {len(ids)} vectors.")
    lines.insert(7, "")
    MANIFEST.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"{verdict}; manifest: {MANIFEST}")
    return 0 if mismatches == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
